name: Deploy to GitHub Pages

on:
  push:
    branches:
      # NOTE: You may want to limit the trigger branch to be "main" or "master" etc.
      - "master"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Generate your content
        run: |
          npm install
          npm run preexport
          npm run export

      - name: Publish current workdir (which contains generated content) to GitHub Pages
        uses: rayluo/github-pages-overwriter@v1.3

        with:

          # Optional. Default value "." means the root directory of your project will be published.
          # You can use whatever directory your project uses, for example "wwwroot".
          # Such a directory does *not* have to already exist in your repo,
          # it could be an output directory created dynamically by your static website builder.
          source-directory: out

          # Optional. Default value "gh_pages".
          # It specifies the temporary branch which hosts the static website.
          # Each build will OVERWRITE this branch.
          target-branch: gh-pages

      - name: Create .nojekyll file in root directory of gh-pages branch, then commit and push it
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          touch .nojekyll
          git add .
          git commit -m "Create .nojekyll file"
          git push origin gh-pages
